# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: tag
    value: 1.0.0

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: "-Dmaven.test.skip=true -Ddockerfile.skip=false"
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    containerRegistry: 'dockerRegistryServiceConnection'
    repository: 'caijunhui/auth-server'
    command: 'push'
    tags: '$(tag)'
