---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - image: caijunhui/auth-server:1.0.0
          imagePullPolicy: IfNotPresent
          name: auth-server
          ports:
            - containerPort: 9000
              name: web
          env:
            - name: APP_OPTS
              value: |
                --spring.cloud.config.discovery.enabled=true
                --spring.datasource.url=jdbc:mysql://127.0.0.1:3306/clientdb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
                --spring.redis.host=127.0.0.1
                --spring.redis.port=6379
            - name: EUREKA_SERVER_ADDRESS
                valueFrom:
                  configMapKeyRef:
                    name: eureka-config
                    key: eureka_service_address
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-X", "POST", "http://localhost:9000/actuator/shutdown"]
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: web
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: web
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  ports:
    - port: 9000
      name: web
      targetPort: web
  selector:
    app: auth-server
