---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - image: caijunhui/auth-server:1.0.0
          imagePullPolicy: IfNotPresent
          name: auth-server
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: web
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: web
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  ports:
    - port: 8080
      name: web
      targetPort: web
  selector:
    app: auth-server
